/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Systeme;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julienpeyrache
 */
public final class Livres extends javax.swing.JFrame {

   Connection con; 
   PreparedStatement pst;
   ResultSet rs;
   
   
    public Livres() {
        initComponents();
        TableLivres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        book_id = new javax.swing.JTextField();
        book_author = new javax.swing.JTextField();
        book_title = new javax.swing.JTextField();
        book_edition = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        text_search = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        book_ISBN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        book_year = new javax.swing.JTextField();
        book_return = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        book_dispo = new javax.swing.JComboBox<>();
        book_state = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Livres");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel1);
        jLabel1.setBounds(208, 6, 468, 59);

        jTable1.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 404, 885, 170);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Titre");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(37, 106, 200, 28);

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Identifiant");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(37, 72, 200, 28);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Edition");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(37, 175, 200, 28);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Auteur(s)");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(37, 141, 200, 28);

        book_id.setBackground(new java.awt.Color(204, 204, 204));
        book_id.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        book_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_idActionPerformed(evt);
            }
        });
        jPanel1.add(book_id);
        book_id.setBounds(255, 72, 260, 28);

        book_author.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jPanel1.add(book_author);
        book_author.setBounds(255, 141, 260, 28);

        book_title.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jPanel1.add(book_title);
        book_title.setBounds(255, 107, 260, 28);

        book_edition.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        book_edition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_editionActionPerformed(evt);
            }
        });
        jPanel1.add(book_edition);
        book_edition.setBounds(255, 176, 260, 28);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton4.setText("Actualiser");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(542, 104, 289, 202);

        jButton5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton5.setText("Rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        text_search.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        text_search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_search.setText("Filtre");
        text_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_searchActionPerformed(evt);
            }
        });
        text_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_search, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(text_search, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(527, 324, 333, 40);

        jButton6.setText("Accueil");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(37, 18, 84, 42);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ISBN");
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(37, 210, 200, 28);

        book_ISBN.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        book_ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_ISBNActionPerformed(evt);
            }
        });
        jPanel1.add(book_ISBN);
        book_ISBN.setBounds(255, 211, 260, 28);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Disponible");
        jLabel7.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(37, 276, 200, 28);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Date parution");
        jLabel8.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(37, 241, 200, 28);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Date de retour");
        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(37, 310, 200, 28);

        book_year.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        book_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_yearActionPerformed(evt);
            }
        });
        jPanel1.add(book_year);
        book_year.setBounds(255, 242, 260, 28);

        book_return.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        book_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_returnActionPerformed(evt);
            }
        });
        jPanel1.add(book_return);
        book_return.setBounds(255, 311, 260, 28);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("État");
        jLabel10.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(37, 345, 200, 28);

        book_dispo.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        book_dispo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oui", "Emprunté" }));
        jPanel1.add(book_dispo);
        book_dispo.setBounds(255, 276, 260, 28);

        book_state.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        book_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Neuf", "Très bon état", "Bon état", "Correct", "Abîmé" }));
        jPanel1.add(book_state);
        book_state.setBounds(255, 345, 260, 28);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jess-bailey-X5gDoysLbBc-unsplash.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, -1, 890, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(885, 596));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void book_editionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_editionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_editionActionPerformed

    private void book_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_idActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Accueil acc = new Accueil();
        acc.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:biblio_v1.db");
            String sql = "insert into livres (book_id, book_title, book_author, book_edition, book_ISBN, book_year, book_dispo, book_state) values (?,?,?,?,?,?,?,?)";
            pst = con.prepareStatement(sql);
            pst.setString(1, book_id.getText());
            pst.setString(2, book_title.getText());
            pst.setString(3, book_author.getText());
            pst.setString(4, book_edition.getText());
            pst.setString(5, book_ISBN.getText());
            pst.setString(6, book_year.getText());
            pst.setString(7, book_dispo.getSelectedItem().toString());
            pst.setString(8, book_state.getSelectedItem().toString());
            pst.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(null, "Ajout du livre réussi");
            TableLivres();
        } 
        catch(Exception e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:biblio_v1.db");
            String sql = "delete from livres where book_id = ?";
            pst = con.prepareStatement(sql);
            pst.setString(1, book_id.getText());
            pst.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(null, "Suppression du livre réussie");
            TableLivres();
        } 
        catch(Exception e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        int i = jTable1.getSelectedRow();
        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        book_id.setText(model.getValueAt(i, 0).toString());
        book_title.setText(model.getValueAt(i, 1).toString());
        book_author.setText(model.getValueAt(i, 2).toString());
        book_edition.setText(model.getValueAt(i, 3).toString());
        book_ISBN.setText(model.getValueAt(i, 4).toString());
        book_year.setText(model.getValueAt(i, 5).toString());
        book_dispo.setSelectedItem(model.getValueAt(i, 6).toString());
        book_state.setSelectedItem(model.getValueAt(i, 7).toString());
    }//GEN-LAST:event_jTable1MouseReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:biblio_v1.db");
            String sql = "update livres set book_title = ?, book_author=?, book_edition=?, book_ISBN=?, book_year=?, book_dispo=?, book_state=? where book_id = ?";
            pst = con.prepareStatement(sql);
            pst.setString(8, book_id.getText());
            pst.setString(1, book_title.getText());
            pst.setString(2, book_author.getText());
            pst.setString(3, book_edition.getText());
            pst.setString(4, book_ISBN.getText());
            pst.setString(5, book_year.getText());
            pst.setString(6, book_dispo.getSelectedItem().toString());
            pst.setString(7, book_state.getSelectedItem().toString());
            pst.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(null, "Modification du livre réussie");
            TableLivres();
        } 
        catch(Exception e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        book_id.setText("");
        book_title.setText("");
        book_author.setText("");
        book_edition.setText("");
        book_ISBN.setText("");
        book_year.setText("");
        book_dispo.setSelectedItem("Oui");
        book_state.setSelectedItem("Neuf");
        
        //text_nat.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void book_ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_ISBNActionPerformed

    private void text_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_searchKeyReleased
        TableLivresRecherche(text_search.getText());
    }//GEN-LAST:event_text_searchKeyReleased

    private void book_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_yearActionPerformed

    private void book_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_returnActionPerformed

    private void text_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_searchActionPerformed
    public void TableLivres(){
        String [] livres = {"book_id", "book_title", "book_author", "book_edition", "book_ISBN", "book_year", "book_dispo", "book_state"};
        String [] afficher = new String[9];
        DefaultTableModel model = new DefaultTableModel(null, livres);
        String sql = "select * from livres";
        
        try{
            Class.forName("org.sqlite.JDBC");
            String url = "jdbc:sqlite:biblio_v1.db";
            String name = "root";
            String pass = "";
            con = DriverManager.getConnection(url, name, pass);
            Statement st = con.createStatement();
            rs = st.executeQuery(sql);
            
            while (rs.next()){
                afficher[0] = rs.getString("book_id");
                afficher[1] = rs.getString("book_title");
                afficher[2] = rs.getString("book_author");
                afficher[3] = rs.getString("book_edition");
                afficher[4] = rs.getString("book_ISBN");
                afficher[5] = rs.getString("book_year");
                afficher[6] = rs.getString("book_dispo");
                afficher[7] = rs.getString("book_state");
                model.addRow(afficher);  
            }
            jTable1.setModel(model);
            con.close();
        } catch(Exception e){
           e.printStackTrace();
        }
    }
    
    public void TableLivresRecherche(String valeur){
        String [] livres = {"book_id", "book_title", "book_author", "book_edition", "book_ISBN", "book_year", "book_dispo", "book_state"};
        String [] afficher = new String[9];
        DefaultTableModel model = new DefaultTableModel(null, livres);
        String sql = "select * from livres where book_id like '%" + valeur+ "%' union select * from livres where book_title like '%" + valeur+ "%' union select * from livres where book_author like '%" + valeur+ "%' union select * from livres where book_edition like '%" + valeur+ "%' union select * from livres where book_ISBN like '%" + valeur+ "%' union select * from livres where book_year like '%" + valeur+ "%' union select * from livres where book_dispo like '%" + valeur+ "%' union select * from livres where book_state like '%" + valeur+ "%'";
        
        try{
            Class.forName("org.sqlite.JDBC");
            String url = "jdbc:sqlite:biblio_v1.db";
            String name = "root";
            String pass = "";
            con = DriverManager.getConnection(url, name, pass);
            Statement st = con.createStatement();
            rs = st.executeQuery(sql);
            
            while (rs.next()){
                afficher[0] = rs.getString("book_id");
                afficher[1] = rs.getString("book_title");
                afficher[2] = rs.getString("book_author");
                afficher[3] = rs.getString("book_edition");
                afficher[4] = rs.getString("book_ISBN");
                afficher[5] = rs.getString("book_year");
                afficher[6] = rs.getString("book_dispo");
                afficher[7] = rs.getString("book_state");
                model.addRow(afficher);  
            }
            jTable1.setModel(model);
            con.close();
        } catch(Exception e){
           e.printStackTrace();
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Livres().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField book_ISBN;
    private javax.swing.JTextField book_author;
    private javax.swing.JComboBox<String> book_dispo;
    private javax.swing.JTextField book_edition;
    private javax.swing.JTextField book_id;
    private javax.swing.JTextField book_return;
    private javax.swing.JComboBox<String> book_state;
    private javax.swing.JTextField book_title;
    private javax.swing.JTextField book_year;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField text_search;
    // End of variables declaration//GEN-END:variables


}
